# spring.application.name=expense-tracker

# # MongoDB Configuration
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=expense_tracker

# # Server Configuration
# server.port=${PORT:8080}





spring.application.name=expense-tracker

# MongoDB Configuration (set MONGODB_URI in Railway environment variables)
spring.data.mongodb.uri=${MONGODB_URI}

# Server Configuration
server.port=${PORT:8080}

# Disable Whitelabel Error Page for better UX
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true
